vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        picture:
            uri_prefix: '%app.path.picture%'
            upload_destination: '%kernel.project_dir%/public%app.path.picture%'
            namer: vich_uploader.namer_uniqid


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
